### ISSUE TITLE
Using "not-os" to build images as a replacement for Linuxkit

### ISSUE THREAD

**Issue by matthewbauer** [nix-community/linuxkit-builder#2]
It would definitely be cool for the Nix ecosystem if we could use not-os here. Has anyone looked into this? not-os can do much of what Linuxkit does (and is built on top of NixOS!)

We would need to provide our own binaries (cross compilation of Linux kerne on Darwin is still broken sadly, mostly from case sensitivity issues, see: https://github.com/matthewbauer/nixpkgs/tree/cross).

**Comment by grahamc** [comment]
I think you've misunderstood the role of linuxkit here. This system is based on NixOS as well, and does not use LinuxKit as the foundational linux system. It uses LinuxKit as the runner. Because of that, I'm going to close this issue.

The name of the project is terrible, I would love an alternative name.

Also, this project will soon be building on hydra.nixos.org, so no real need for cross compilation.
